# Generated by Django 2.0 on 2019-04-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_list',
            new_name='blog_type',
        ),
    ]
